name: ping supabase api

on:
  schedule:
    - cron: "0 0 * * 1,4"
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: ping database
        run: |
          # psql "$DATABASE_URL" -c "SELECT 1;"
          curl -s -X GET "${SUPABASE_URL}/rest/v1/" \
          -H "apikey: ${SUPABASE_KEY}" \
          -H "Authorization: Bearer ${SUPABASE_KEY}"
        env:
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SECRET }}
